### ISSUE TITLE
How can I run for X minutes?

### ISSUE THREAD

**Issue by ben-ix** [laic-ufmg/Recipe#3]
Hi there,

Thanks for the software. I would like to run a time equated comparison.
Is there a way to run for say X minutes? 

The only way I can see would be to set an individual timeout, and then ensure
population size * generations * timeout <  X minutes

If theres a better way please let me know.
Thanks

**Comment by walterjgsp** [comment]
Hi Ben,

First i like to thank you for using the RECIPE, i hope that the algorithm is helping you. 

This is one of the features that we are looking to implement in the RECIPE, since TPOT and AutoSk already have it. Right now, to ensure the timeout is just like you stated : population size * generations * timeout < X minutes

Sorry for the trouble,
Thanks.

**Comment by ben-ix** [comment]
Thank you for the response, an the timeout is specified in seconds, correct?

**Comment by walterjgsp** [comment]
Hi Ben,

The timeout is specified in seconds, that is correct. 

Regards the results, we cached  them so that the execution of the experiments are faster, in a way that we not recalculate the same pipeline again for the same context. Cleaning cache is a feature that we are thinking to implement in the future. One thing that i do it is to move away the folders where cache is saved: "fitmap", "results" and "evolution".

Thanks for using RECIPE,
Any question just ask.

**Comment by walterjgsp** [comment]
Hi Ben,

Now a timeout was implemented in the algorithm, you can use the flag -ft (time in seconds) when executing that will apply for X minutes.

**Comment by ben-ix** [comment]
Thanks for adding that. Just tested it and it works well, not sure if you want to make the progress bar reflect the time left or the percentage of generations completed now
