### ISSUE TITLE
Missing values 

### ISSUE THREAD

**Issue by ben-ix** [laic-ufmg/Recipe#4]
Hi there,

Me again. Thought I would open a new issue as the two are not related.

RECIPE seems to work with missing values, are these supported by default or is it simply discarding pipelines which do not have an imputer step, or treating missing values as a constant or something else entirely? (missing values are represented as a ? in csv, so Im curious if this is being treated as a category). I see some of the sample datasets have "NaN", so should this be used over the "?" ?

Thanks,
Ben

**Comment by alexgcsa** [comment]
Hi Ben,

We used "NaN" instead of "?" (in RECIPE) to indicate a missing value.  This is a default option in the scikit-learn library. We decided to maintain it. So, when an imputation approach identifies a "NaN", it will replace it. In RECIPE, we allow three approaches, i.e., replacing the missing value by the mean, the median or the most frequent  along the respective attribute column.  You can check this information in the following URL:

http://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer

As far as I know, "?" is commonly used in the WEKA framework. We could used it, but we kept the default option.

Cheers,

Alex de Sá

**Comment by ben-ix** [comment]
Awesome,

Thanks! Yeah the "?" is the standard in weka and UCI repository, and NaN elsewhere.

I'll close the issue now

**Comment by alexgcsa** [comment]
We do not discard the pipelines. We simply run the pipeline in the dataset with missing values, Hence, it is basically handled as a constant when the imputation is not performed previously.

Cheers,

Alex de Sá
